[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/get-upload-url"
  to = "/.netlify/functions/get-upload-url"
  status = 200

[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/api/upload-multiple"
  to = "/.netlify/functions/upload-multiple"
  status = 200
